# Generated by Django 4.2 on 2023-04-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=128)),
                ('animal_description', models.CharField(max_length=2000)),
                ('animal_weight', models.CharField(max_length=128)),
                ('animal_length', models.CharField(max_length=128)),
                ('animal_habitat', models.CharField(max_length=128)),
                ('animal_fact1', models.CharField(blank=True, max_length=256, null=True)),
                ('animal_fact2', models.CharField(blank=True, max_length=256, null=True)),
                ('animal_fact3', models.CharField(blank=True, max_length=256, null=True)),
                ('animal_sound', models.CharField(blank=True, max_length=128, null=True)),
                ('animal_image1', models.CharField(blank=True, max_length=128, null=True)),
                ('animal_image2', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
