# Generated by Django 4.2 on 2023-05-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_remove_animal_animal_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_image1',
            field=models.ImageField(blank=True, null=True, upload_to='archives/static/images'),
        ),
    ]
