# Generated by Django 4.2 on 2023-05-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_alter_animal_animal_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
